### ISSUE TITLE
Query custom scalar property

### ISSUE THREAD

**Issue by luvies** [acro5piano/typed-graphqlify#33]
Would it be possible to add the ability to query custom scalar types? For example, the API I'm building uses  the JSON type from [graphql-type-json](https://github.com/taion/graphql-type-json), and the client needs to query on this field.

I know what the type of this field will be (since the data come from elsewhere, so structure is a given), so something like
```ts
const queryObject = {
  getData: {
    data: types.custom<Array<Record<string, ...>>>(),
  },
}
```

Currently my workaround is to do:
```ts
export const extypes = {
  custom<T>(): T {
    return '' as any;
  },
};
```
and import it separately.

**Comment by acro5piano** [comment]
Thanks for your interest in typed-graphlify!

I confirmed the issue and add minimal code. I don't know much about custom scalar type, so could you review it?

https://github.com/acro5piano/typed-graphqlify/pull/34

If you would like, you can re-submit my PR so that you can become a contributor of this project!

**Comment by luvies** [comment]
I've looked through it, and it looks good. Thanks for the quick reponse on this.
